[package]
name = "meiling"
version = "0.1.0"
authors = ["Joosung Park <admin@slowmotion.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
juniper = "0.14"
serde = "1"
serde_json = "1"
